name: "Fix PHP code style issues"

on:
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.6

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fix styling [skip ci]"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
